name: CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  build:
    name: Build, Test and Dockerize
    runs-on: ubuntu-latest

    steps:
      # 1. Descargar c√≥digo
      - name: Checkout source code
        uses: actions/checkout@v4

      # 2. Instalar Java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      # 3. Build + Tests
      - name: Build and run tests
        run: mvn clean verify

      # 4. Build imagen Docker
      - name: Build Docker image
        run: docker build -t banking-ms:ci .
